### ISSUE TITLE
`yarn build` is failing after adding `ErrorBoundry`

### ISSUE THREAD

**Issue by gabhijit** [hyphenOs/pkt-trail-react#40]
I am trying to get this working with 'Demo' UI. The previous version is working fine with demo UI, However after `ErrorBoundry` is added, `yarn build` fails, **Note: `yarn test` still succeeds**. 

See attached log - 

```shell
yarn build
yarn run v1.22.4
$ rm -rf dist && NODE_ENV=production babel src/lib --out-dir dist --copy-files --ignore __tests__,spec.js,test.js,__snapshots__
{ SyntaxError: /home/gabhijit/Work/hyphenOs/webshark-frontend/src/lib/components/ErrorBoundary.js: Support for the experimental syntax 'classProperties' isn't currently enabled (5:9):

  3 | 
  4 | class ErrorBoundary extends React.Component {
> 5 |   state = { hasError: false };
    |         ^
  6 | 
  7 |   static getDerivedStateFromError(error) {
  8 |     return { hasError: true };

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
    at Object._raise (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:764:17)
    at Object.raiseWithData (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:757:17)
    at Object.expectPlugin (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:8932:18)
    at Object.parseClassProperty (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12363:12)
    at Object.pushClassProperty (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12323:30)
    at Object.parseClassMemberWithIsStatic (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12256:14)
    at Object.parseClassMember (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12193:10)
    at withTopicForbiddingContext (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12141:14)
    at Object.withTopicForbiddingContext (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:11206:14)
    at Object.parseClassBody (/home/gabhijit/Work/hyphenOs/webshark-frontend/node_modules/@babel/parser/lib/index.js:12118:10)
  loc: Position { line: 5, column: 8 },
  pos: 127,
  missingPlugin: [ 'classProperties' ],
  code: 'BABEL_PARSE_ERROR' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mayurhyphenOs** [comment]
Fixed in Pull #41  by defining state in the constructor instead of "classProperties" syntax in ErrorBoundary component
